default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: perf_check_ci_development

test:
  <<: *default
  database: perf_check_ci_test

production:
  <<: *default
  database: perf_check_ci_production